### PR TITLE
Release version v0.9.0

### PR DESCRIPTION
**Pull request by michael-valdron**
### What does this PR do?:

Release changes for AI Software Templates v0.9.0.

### Which issue(s) this PR fixes:

https://issues.redhat.com/browse/DEVAI-185

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened and linked to this PR, if they are not in the PR scope due to various constraints.

- [ ] Tested and Verified

  

- [X] Documentation (READMEs, Product Docs, Blogs, Education Modules, etc.)

### CODE REVIEW

**Comment by Jdubrick** [comment]
Should we pull the change from here into this PR? @michael-valdron https://github.com/redhat-ai-dev/ai-lab-app/pull/36

**Review by johnmcollier — COMMENTED** [review]
We should add the LICENSE file (Apache 2) to the release branch.

(It needs to be added to main as well)

**Comment by michael-valdron** [comment]
> Should we pull the change from here into this PR? @michael-valdron [redhat-ai-dev/ai-lab-app#36](https://github.com/redhat-ai-dev/ai-lab-app/pull/36)

https://github.com/redhat-ai-dev/ai-lab-template/pull/46

**Comment by michael-valdron** [comment]
> We should add the LICENSE file (Apache 2) to the release branch.
> 
> (It needs to be added to main as well)

@johnmcollier  We'll need to open PRs into all the same repositories to first target main, I can rebase the outstanding release PRs and create new ones to merge in the changes into those I've already merged.

**Comment by michael-valdron** [comment]
> We should add the LICENSE file (Apache 2) to the release branch.
> 
> (It needs to be added to main as well)

#47

**Review by maysunfaisal — APPROVED** [review]
tried out chatbot on OpenShift and RHOAI 👍

**Pull request merged**
